### ISSUE TITLE
Shall joomla continue with the same folders structure?

### ISSUE THREAD

**Issue by dgt41** [mbabker/joomla-next#4]
One thing that will help joomla-next to run without mods in google app engine and other such environments is the separation between the functional code and the static assets. And why not re-structrure the whole thing for simplicity and better maintenance?
My view will be something like:
![screen shot 2015-03-24 at 10 23 19](https://cloud.githubusercontent.com/assets/3889375/6812119/6e9a2260-d275-11e4-9137-2a51e79aa419.png)

By the way intentionally there are no administrator, media, images etc folders as these have to be decided if needed, how they’re gonna be named etc

**Comment by mbabker** [comment]
Right now it's just a skeleton based on the existing structure.  There's room to play with it, but one of the rules has to be that the package is still fully installable at the web root.  I think we take a huge market hit if there's an expectation that any Joomla source code is `*REQUIRED*` to live outside the web root.  However, the app structure should be fully coded in a way that this `*CAN*` happen without core hacks.

**Comment by wilsonge** [comment]
Don't forget with any reorganization that by default Joomla needs to be run inside the public directory of a host as many people on cheap hosting providers (the silent majority of our user base) don't have permissions outside of this directory

**Comment by vess** [comment]
It would be really nice to only have a very small set of folders in the root directory, for example a src and www folder, where all server side code resides in src and all stuff like images, css, js etc. goes into the www folder.
From an extension developer point of view it would be nice to have landing pages like
url.com/templates
url.com/plugins
etc.

**Comment by mbabker** [comment]
The distributed package should be installable in the web root and usable
without requiring nginx, IIS, or Apache configs.  I don't think we can
change this requirement without making installing and using Joomla more
complex.  Even this last update with the post-install messages suggesting
updates to the robots.txt and htaccess files caused a bit of confusion on
the forums.

With that said, I do support efforts to consolidate the number of top level
folders, and making it possible for advanced users to move Joomla's code
around in the filesystem.  This means well defined path defines I think and
well defined coding practices around them (such as using JPATH_PLUGINS to
scan the plugins folder instead of JPATH_ROOT.'/plugins').

**Comment by vess** [comment]
>The distributed package should be installable in the web root...

Absolutely! It was not my intention to suggest something else.
See attached image, if you create a custom defines.php where you change the SRC_PATH to a path outside of your web root the application has no problems with this.
![Uploading Untitled.png . . .]()

**Comment by dgt41** [comment]
Also in defines we can specify the configuration e.g. `configuration-dev.php`, `configuration-testing.php` and `configuration.php` as an easy way to have development/testing/live environments. Of course database is another consideration in these cases...

**Comment by vess** [comment]
Doesn't seem to like my image and is not uploading it...
However, like you already wrote @mbabker the path defines are the key here, there is one for the src path and then the others are defined like this `define('PLUGINS_PATH', SRC_PATH .'/Plugins');`

The idea for different configs is also nice @dgt41

**Comment by mbabker** [comment]
> See attached image, if you create a custom defines.php where you change the SRC_PATH to a path outside of your web root the application has no problems with this.

You can already override the defines in the CMS (https://github.com/joomla/joomla-cms/blob/staging/index.php#L25) and this code (https://github.com/mbabker/joomla-next/blob/master/index.php#L23).  I've never tried it, but in theory you should be able to move core around.  I can't say much for extensions though.

**Comment by mbabker** [comment]
I guess you might also have some issues with the media override functionality of JHtml's asset loader methods (see https://github.com/mbabker/joomla-next/blob/master/libraries/core/Renderer/Helper/MediaTrait.php#L128 which is my first extraction of that code from the CMS repo for an example.

**Comment by dgt41** [comment]
@mbabker looking at this nice trait file a question came up: do we need a joomla browser lib? can’t we just use https://github.com/cbschuld/Browser.php

**Comment by vess** [comment]
I know that you can override defines.php already but right now you will for sure run into some problems with moving core around  guess, but also never tested it.
Btw $rootUri is not defined in that Trait if I did look correctly, can it be that https://github.com/mbabker/joomla-next/blob/master/libraries/core/Renderer/Helper/MediaTrait.php#L53 should be start with $rootUri instead of $baseUri?

**Comment by mbabker** [comment]
@dgt41 The browser library question came up on the Framework list.  Personally I could care less; I just went with what we already had as the quickest implementation to get rolling with.

@vess - Yep, that's an error.  Shouldn't be writing code after midnight :wink:

**Comment by wilsonge** [comment]
@dgt41
https://groups.google.com/forum/?fromgroups=#!topic/joomla-dev-framework/U8QERx35wDA
I investigated alternatives to JApplicationClient including the one you
linked last week. Nothing was perfect but we could help ourselves in places.

Kind Regards,
George
